version: '3'

services:
    locker-backend:
        build: ./server
        image: locker-backend
        container_name: locker-backend
        working_dir: /app
        ports:
            - "3001:3000"
        expose:
            - "3001"
        networks:
            - locker-network
        volumes:
            - ~/.kube:/root/.kube
            - ~/.aws:/root/.aws
# Uncomment the following to override the list namespace request to k8s
#       environment:
#           - NAMESPACES=namespace-one,namespace-two
    locker-frontend:
        build: ./client
        image: locker-frontend
        container_name: locker-frontend
        working_dir: /app
        ports:
            - "3000:3000"
        expose:
            - "3000"
        networks:
            - locker-network
        depends_on:
            - locker-backend

networks:
    locker-network:
